spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
server:
  port: 8761

